table _Measures
	lineageTag: 45089009-fab9-48ba-bad5-5a5f2d17346c

	measure 'Defect Quantity' = CALCULATE(SUM('Supplier Quality'[Total Defect Qty]))
		formatString: #,0
		lineageTag: c795c066-31a3-4c54-af65-89823c0bc5b2

	measure 'Total Downtime' = ```
			
			DIVIDE(
			        SUM('Supplier Quality'[Total Downtime Minutes]),
			        60, 
			        0
			)
			
			```
		lineageTag: 23fe3160-d76c-424d-8943-ecf328e03403

		formatStringDefinition = "0,0" & " Hours"

	measure 'Percentage of Total Defect Qty' =
			
			VAR _TotalQty = [Total Defect Quantity]
			VAR _SelectedQty = [Defect Quantity]
			RETURN DIVIDE(_SelectedQty,_TotalQty,0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 252c082c-2dd4-435f-baa7-4605c7806edc

	measure 'Total Defect Quantity' = CALCULATE(SUM('Supplier Quality'[Total Defect Qty]), ALL('Supplier Quality'))
		formatString: 0
		lineageTag: 3fec1bf5-864b-4ee5-b7b1-20822a30a1e8

	measure 'Defect Rank' = ```
			RANKX('Supplier Quality', [Defect Quantity], , DESC, Dense)
			
			```
		formatString: 0
		lineageTag: e5764a1f-6489-4ba5-af43-184184114b8b

	measure Plant = SELECTEDVALUE(Plant[Plant])
		lineageTag: c23ad7f6-0ccb-49a2-91b1-6e57cb5a3ee5

	measure 'Top N Defect Quantity' = ```
			
			VAR SelectedN = 'TopN'[TopN Value]
			RETURN
			CALCULATE(
			    [Defect Quantity],
			    KEEPFILTERS(
			            TOPN(
			            SelectedN, 
			        ALLSELECTED(Plant[Plant]), 
			            [Defect Quantity], 
			            DESC
			            )
			    )
			)
			```
		formatString: 0
		lineageTag: 597c682f-a148-4d36-9a8a-60673c13418e

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

