table Date
	lineageTag: 0c413a38-14ac-40d9-80b3-1be8aec6466a
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: afc46d9c-3fd1-4ae3-b43f-09ee9fec68f7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9f99132b-b316-4ed1-93b0-3ca6c17f4f0e
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 8e976e9c-9a0f-4c99-acd4-06bab13d4f50
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 47217e54-a31a-4518-b06a-f05e8a943a6a
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 86eeeed9-a1b9-43fc-a88a-7e7382a2dcd4
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 422f27a5-4cec-4e77-a5b6-07dd246e1910
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8646de4f-60e3-43d5-8ac0-ee196cc0dc33
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = List.Min(#"Supplier Quality"[Date]),
				    Custom1 = List.Dates (Source, Number.From(List.Max(#"Supplier Quality"[Date]))+ 1 - Number.From(Source), #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Custom1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Month Name", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Day Name", "Quarter", each "Q" &  Text.From(Date.QuarterOfYear([Date])) & "-" & Text.From(Date.Year([Date])), type text)
				in
				    #"Inserted Quarter"

	annotation PBI_ResultType = Table

